# Generated by Django 3.2 on 2021-04-26 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.TimeField(verbose_name='Время отправления')),
                ('arrival_time', models.TimeField(verbose_name='Время прибытия')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bus', verbose_name='Автобус')),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_point', models.CharField(max_length=255, verbose_name='Пункт отправления')),
                ('destination', models.CharField(max_length=255, verbose_name='Пункт назначения')),
                ('travel_time', models.TimeField(verbose_name='Время в пути')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.race', verbose_name='Рейс')),
            ],
        ),
    ]
