# Generated by Django 3.2 on 2021-04-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name': 'Автобус', 'verbose_name_plural': 'Автобусы'},
        ),
        migrations.AlterModelOptions(
            name='race',
            options={'verbose_name': 'Рейс', 'verbose_name_plural': 'Рейсы'},
        ),
        migrations.AlterModelOptions(
            name='routes',
            options={'verbose_name': 'Маршрут', 'verbose_name_plural': 'Маршруты'},
        ),
        migrations.AddField(
            model_name='race',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
