# Generated by Django 3.2 on 2021-05-02 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210430_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routes',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='routes',
            name='race',
        ),
        migrations.AddField(
            model_name='race',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.routes', verbose_name='Маршрут'),
        ),
    ]
