# Generated by Django 3.2 on 2021-05-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210502_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routes',
            name='departure_point',
        ),
        migrations.RemoveField(
            model_name='routes',
            name='travel_time',
        ),
        migrations.AddField(
            model_name='routes',
            name='first_point_of_departure',
            field=models.CharField(max_length=255, null=True, verbose_name='Первая точка отправления'),
        ),
        migrations.AddField(
            model_name='routes',
            name='second_point_of_departure',
            field=models.CharField(max_length=255, null=True, verbose_name='Вторая точка отправления'),
        ),
    ]
