# Generated by Django 3.2 on 2021-05-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210502_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='race',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='race',
            name='route',
        ),
        migrations.AddField(
            model_name='race',
            name='first_point_of_departure',
            field=models.CharField(max_length=255, null=True, verbose_name='Первая точка отправления'),
        ),
        migrations.AddField(
            model_name='race',
            name='first_shedule',
            field=models.TextField(null=True, verbose_name='Расписание'),
        ),
        migrations.AddField(
            model_name='race',
            name='second_point_of_departure',
            field=models.CharField(max_length=255, null=True, verbose_name='Вторая точка отправления'),
        ),
        migrations.AddField(
            model_name='race',
            name='second_shedule',
            field=models.TextField(null=True, verbose_name='Расписание'),
        ),
        migrations.DeleteModel(
            name='Routes',
        ),
    ]
