# Generated by Django 3.2 on 2021-05-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210512_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='ticket_price',
            field=models.PositiveSmallIntegerField(default=0, help_text='Указывать сумму в рублях', verbose_name='Цена билета'),
        ),
    ]
