# Generated by Django 3.2 on 2021-05-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_race_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='route',
            field=models.TextField(null=True, verbose_name='Маршрут следования'),
        ),
    ]
