# Generated by Django 3.2 on 2021-05-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210516_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='ticket_price',
            field=models.CharField(max_length=255, verbose_name='Цена билета'),
        ),
    ]
