# Generated by Django 3.2 on 2021-05-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_race_ticket_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suburban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_point', models.CharField(max_length=255, verbose_name='Начальный пункт')),
                ('terminus', models.CharField(max_length=255, verbose_name='Конечный пункт')),
                ('departure_time', models.TextField(verbose_name='Время отправления')),
            ],
            options={
                'verbose_name': 'Маршрут электрички',
                'verbose_name_plural': 'Маршрут электричек',
            },
        ),
    ]
