# Generated by Django 3.2 on 2021-05-27 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_suburban'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suburban',
            options={'verbose_name': 'Электричка', 'verbose_name_plural': 'Электрички'},
        ),
    ]
